export const SET_MOBILE_SCREEN = "SET_MOBILE_SCREEN";
export const UNSET_MOBILE_SCREEN = "UNSET_MOBILE_SCREEN";
export const SET_PHONE_SCREEN = "SET_PHONE_SCREEN";
export const UNSET_PHONE_SCREEN = "UNSET_PHONE_SCREEN";
